# XXX - Rename this file to just "packages.yaml", including in main.yml.
---
# Install prerequisites

- name: Install prerequisites (apt)
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - python3-jmespath
    - libnss3-tools
  when:
    - ansible_pkg_mgr == "apt"

- name: Install prerequisites (Macports)
  become: yes
  macports:
    name: "{{ item }}"
  with_items:
    # Needed to make Python curl work.
    #
    # curl-ca-bundle includes a certificate chain to authenticate
    # mozilla URLs.
    - curl-ca-bundle
    - py-jmespath
    - nss
  when:
    - ansible_pkg_mgr == "macports"
