---
# Parameters:
# - certificate: Certificate to add. Has subfields:
#   - name: Human-friendly name of the certificate, like "Homelab CA"
#   - path: Path to the certificate file, e.g.,
#	/home/user/homelabCA.pem

- name: "Delete existing certificate {{ certificate.name }}"
  vars:
    profile_subdir: "{{ firefox_dir }}/{{ profiles.profiles[profile].path | default('dummy') }}"
  ansible.builtin.command:
    argv:
      - certutil
      - -D
      - -n
      - "{{ certificate.name }}"
      - -d
      - "sql:{{ profile_subdir }}"
  failed_when: false

- name: "Add certificate {{ certificate.name }}"
  vars:
    profile_subdir: "{{ firefox_dir }}/{{ profiles.profiles[profile].path | default('dummy') }}"
  ansible.builtin.command:
    argv:
      - certutil
      - -A
      - -n
      - "{{ certificate.name }}"
      - -t
      - "{{ certificate.trustargs | d('CT,C,') }}" 
      - -i
      - "{{ certificate.path }}"
      - -d
      - "sql:{{ profile_subdir }}"
